### ISSUE TITLE
Instalace za proxy

### ISSUE THREAD

**Issue by LesniDrat** [ctu-geoforall-lab/qgis-ruian-plugin#4]
Problem pri instalaci zasuvneho modulu.
Sedim za firemni proxy. Ke komunikaci s webem je pozadovana autentizace. Bezne webove sluzby, napr. wms/wfs po nastaveni proxy v Settings/Options normalne funguji.

Instalace RUIAN modulu konci po stahovani dat chybou:
![ruianpluginerror](https://user-images.githubusercontent.com/31921955/30374464-55f24f7a-9885-11e7-8efb-102b97d4d814.png)
![ruianpluginerror2](https://user-images.githubusercontent.com/31921955/30374490-6c94410c-9885-11e7-9d93-b331d240530d.png)

This plugin is broken
HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ctu-geoforall-lab/gdal-vfr/archive/v2.0.4.zip (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))

...

Couldn't load plugin qgis-ruian-plugin-master due to an error when calling its classFactory() method 

ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ctu-geoforall-lab/gdal-vfr/archive/v2.0.4.zip (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))

**Comment by landam** [comment]
@LesniDrat Muzete prosim zkusit znovu? Nedavno jsem prepnul na zalozni HTTP, https://github.com/ctu-geoforall-lab/qgis-ruian-plugin/commit/749fffe4ed42d7690fd299f03c836071bb790738

**Comment by landam** [comment]
gdal-vfr je nyni soucasti instalacniho balicku.
